kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-broker0
spec:
  replicas: 1
  selector:
    matchLabels:
        app: kafka
        id: "0"
  template:
    metadata:
      labels:
        app: kafka
        id: "0"
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka:3.0.0
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name  : KAFKA_CFG_LISTENERS
          value : "CLIENT://:9092,EXTERNAL://:9093"
        - name  : KAFKA_CFG_ADVERTISED_LISTENERS
          value : "CLIENT://$(KAFKA_POD_IP):9092,EXTERNAL://localhost:9093"
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zk-s:2181
        - name: KAFKA_BROKER_ID
          value: "0"
        - name:  ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name  : KAFKA_CFG_INTER_BROKER_LISTENER_NAME
          value : "CLIENT"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    name: kafka
spec:
  ports:
  - port: 9092
    #nodePort: 30092
    name: kafka-internal
    protocol: TCP
  - port: 9093
    #nodePort: 30093
    name: kafka-external
    protocol: TCP
  selector:
    app: kafka
    id: "0"
  type: LoadBalancer

