apiVersion: v1
kind: ConfigMap
metadata:
  name: general-config
data:
  #BROKER
  BROKER_HOST: "rabbitmq-service"
  #BROKER_PORT_AMQP: "5672"
  BROKER_PORT_MQTT: "1883"
  #BROKER_MANAGEMENT_PORT: "15672"
  #CA_FILE: ""
  #CLIENT_CERT_FILE: ""
  #CLIENT_KEY_FILE: ""

  #KAFKA
  kafka.uri: "kafka-service:9092"

  #MINIO
  MINIO_ENDPOINT: "http://my-minio:9000"

  #MEMCACHED
  MEMCACHED_HOST: "my-memcached"
  MEMCACHED_PORT: "11211"

  #MYSQL
  spring.datasource.url: "jdbc:mysql://my-mysql:3306/my_database"

  #MS
  ONLY_SAVE_MEASUREMENT_VALUE: "true"

  BUCKET_NAME: spark-test
  #todo:
  application.batch.intervals: HOUR,DAY

  #TEMPERATURE
  TEMPERATURE_TOPIC_PATTERN: data.aggregator.temperature.*
  TEMPERATURE_SENSOR_TYPE: temperature
  EXPORT_TEMPERATURE_DATA_AS_METRIC: "true"

  #HUMIDITY
  HUMIDITY_TOPIC_PATTERN: data.aggregator.humidity.*
  HUMIDITY_SENSOR_TYPE: humidity
  EXPORT_HUMIDITY_DATA_AS_METRIC: "true"

  #TEMPERATURE AGGREGATOR
  TEMPERATURE_AGGREGATOR_GROUP_TYPE_NAME: temperature-group

  #HUMIDITY AGGREGATOR
  HUMIDITY_AGGREGATOR_GROUP_TYPE_NAME: humidity-group

  #EXPORTER
  EXPORT_SENSOR_DATA: "true"
  EXPORT_SENSOR_DATA_TYPES: ALL
  EXPORT_AGGREGATOR_DATA_TYPES: ALL
  #EXPORT_START_WITH_ID=1
  #EXPORT_END_WITH_ID=30

  #VIRTUALIZATION
  OPEN_WEATHER_API_KEY: "a82a6669f501863632f16529cff1f36a"
  OPEN_WEATHER_API_CITIES: 2842647,524901,6255152,3169070,5128581,1850147,2899449,2871675,2864435,2842632,2841463,2825297,2867714,2950159,2852458,2944388,2911298,2809346,2834282,2910831,2934246,2874225,2935022,2874545,2891122,2929670
  #TEMPERATURE_AGENT_COUNT: "0"
  #HUMIDITY_AGENT_COUNT: "0"
  #PICTURE_AGENT_COUNT: "0"
  #WATER_AGENT_COUNT: "0"
  #AIRQUALITY_AGENT_COUNT: "0"
  SIMULATION_INTERVAL: "30"

  spring.jpa.show-sql: "false"
  logging.level.org.hibernate: ERROR
  logging.level.org.hibernate.type: ERROR


---

apiVersion: v1
kind: Secret
metadata:
  name: general-secrets
type: Opaque
stringData:
  #BROKER
  BROKER_USERNAME: guest
  BROKER_PASSWORD: guest

  #MINIO
  MINIO_ACCESSKEY: admin
  MINIO_SECRETKEY: lRRxhv4CwD

  #MYSQL
  spring.datasource.username: root
  spring.datasource.password: lcsxwJISbK

